IMAGE_PROCESSING:
  BACKGROUND_COLOR: 250
  BLUR_KERNEL: 3
  EROSION_ITERATIONS: 50
  EROSION_KERNEL: 21
  MARGIN: 20
  THRESHOLD: 35
  THRESH_INVERTED: false
IO:
  DEVICE_PATH: images\
  IMAGE_EXTENSION: JPG
  IMAGE_PREFIX: IMAG
  LAST_IMAGE_IDX: 0
  READ_GRAYSCALE: false
  SAVE_DPI: 300
  SAVE_FORMAT: pdf
  SAVE_PATH: output\
  SAVE_PREFIX: SCAN
